### ISSUE TITLE
wrong task naming

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-java#1]
### Type of Report

bug

### Actual behaviour

tasks in main.yml are named postfix, even variables...

https://github.com/while-true-do/ansible-role-java/blob/de52e751b516ec5d2bb588e6501f5ce2af30aa4e/tasks/main.yml#L4-L7

### Expected behaviour

tasks and attributes should be named to "java"

**Comment by daniel-wtd** [comment]
Ooopsi... will fix it asap.
